import fs from 'fs'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../../components/Footer'
import styles from '/styles/Projects.module.css'

const Projects = ({ id }: any) => {
	return (
		<>
		<div className={styles.container}>
		<Head>
			<title>Projects</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className={styles.main}>
			<h1 className={styles.title}>
			Welcome to my Projects
			</h1>

			<div className={styles.grid}>
                    <a className={styles.card}>
                        <h1>Resume Site</h1>
                        <p>This site! The purpose of this project is the create a site that can be navigated to understand me. The value I&#39;ll bring to your team and just general information about me. Check out the Github repository for this site <a href='https://github.com/tsar-boomba/my-site-project'>here.</a></p>
                    </a>

			</div>

		</main>

		</div>
			<div className={styles.footer}>
				<Footer />
			</div>
		</>
	)
}

export const getStaticProps = async () => {
	const files = fs.readdirSync('posts')
	return {
		props: {
			id: files.map(filename => filename.replace('.md', ''))
		}
	}
}

export default  Projects;