import fs from 'fs'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'
import profilePic from '/public/profilePic.jpg'

const Home = ({ id }: any) => {
	return (
		<>
		<div className={styles.rowtainer}>
			<div className={styles.container}>
			<Head>
				<title>Isaiah Gamble</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
				Welcome to Isaiah Gamble!
				<Image className={styles.profilepic} src={profilePic} alt='me!' />
				</h1>

				<div className={styles.grid}>
					<a href="/music" className={styles.card}>
						<h2>Music &rarr;</h2>
						<p>See what music I&#39;m into right now</p>
					</a>

					<a href="/posts" className={styles.listcard}>
						<h2>Posts &rarr;</h2>
						<p>Check out the posts I&#39;ve made</p>
					</a>

					<a href="/projects" className={styles.card}>
						<h2>Projects &rarr;</h2>
						<p>Check out the cool stuff I&#39;ve done</p>
					</a>

					<a href="https://github.com/tsar-boomba" className={styles.card}>
						<h2>GitHub &rarr;</h2>
						<p>Check out the source code for all of the stuff I&#39;ve done</p>
					</a>

				</div>

			</main>
			</div>
		</div>
			<div className={styles.footer}>
				<Footer />
			</div>
		</>
	)
}

export const getStaticProps = async () => {
	const files = fs.readdirSync('posts')
	return {
		props: {
			id: files.map(filename => filename.replace('.md', ''))
		}
	}
}

export default Home;
