import fs from 'fs'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home = ({ id }: any) => {
	return (
		<div className={styles.container}>
		<Head>
			<title>Isaiah Gamble</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className={styles.main}>
			<h1 className={styles.title}>
			Welcome to Isaiah Gamble!
			</h1>

			<div className={styles.grid}>
				<a href="https://open.spotify.com/user/zeekiosk" className={styles.card}>
					<h2>Music &rarr;</h2>
					<p>See what music I&#39;m into right now</p>
				</a>

				<a href="/posts" className={styles.listcard}>
					<h2>Posts &rarr;</h2>
					<p>Check out the posts I&#39;ve made</p>
				</a>

				{/* <a href="https://nextjs.org/learn" className={styles.card}>
					<h2>Learn &rarr;</h2>
					<p>Learn about Next.js in an interactive course with quizzes!</p>
				</a>

				<a
					href="https://github.com/vercel/next.js/tree/master/examples"
					className={styles.card}
				>
					<h2>Examples &rarr;</h2>
					<p>Discover and deploy boilerplate example Next.js projects.</p>
				</a>

				<a
					href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					className={styles.card}
				>
					<h2>Deploy &rarr;</h2>
					<p>
					Instantly deploy your Next.js site to a public URL with Vercel.
					</p>
				</a> */}
			</div>
			<div className={styles.container}>
				
			</div>
		</main>

		</div>
	)
}

export const getStaticProps = async () => {
	const files = fs.readdirSync('posts')
	return {
		props: {
			id: files.map(filename => filename.replace('.md', ''))
		}
	}
}

export default  Home;
